#!/bin/sh
# Bakes the test binaries into web/samples.js as base64, so the demo page has
# something to run without the visitor needing an .exe on hand.
set -e
cd "$(dirname "$0")/.."
out=web/samples.js

emit() {                        # emit <key> <label> <file>
    [ -f "$3" ] || { echo "  skip $3 (not built)"; return; }
    printf '  { key: "%s", label: "%s", data: "' "$1" "$2" >> $out
    base64 -w0 < "$3" >> $out
    printf '" },\n' >> $out
    echo "  + $2"
}

echo "// Generated by web/make_samples.sh - do not edit." > $out
echo "globalThis.X86EMU_SAMPLES = [" >> $out
emit hello32    "hello (PE32, 32-bit Windows)"   tests/bin/hello32.exe
emit hello64    "hello (PE32+, 64-bit Windows)"  tests/bin/hello64.exe
emit arith64    "arithmetic torture (64-bit)"    tests/bin/arith64.exe
emit insn64     "instruction tests (64-bit)"     tests/bin/insn64.exe
emit elf32      "hello (ELF32, 32-bit Linux)"    tests/bin/hello_elf32
emit elf64      "hello (ELF64, 64-bit Linux)"    tests/bin/hello_elf64
# Built by a stock Visual Studio toolchain: the CRT startup runs before main.
emit msvc32     "Visual Studio /MD (32-bit)"     tests/msvc/bin/fmt_msvc_MD32.exe
emit msvc64     "Visual Studio /MD (64-bit)"     tests/msvc/bin/fmt_msvc_MD64.exe
emit msvcmt64   "Visual Studio /MT (64-bit)"     tests/msvc/bin/fmt_msvc_MT64.exe
echo "];" >> $out
ls -l $out
