// Proves emu_run_path: put a program into the emscripten filesystem, run it by
// path with a real argv, and check its output - the plumbing the browser CPython
// needs (load a file from MEMFS instead of a byte array, pass argv).
//
//   node web/test_run_path.mjs
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import fs from 'node:fs';
import path from 'node:path';

const require = createRequire(import.meta.url);
const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(here, '..');
const createX86Emu = require(path.join(here, 'x86emu.js'));

let out = '';
const decoder = new TextDecoder();
globalThis.x86emuOutput = (fd, bytes) => { out += decoder.decode(bytes, { stream: true }); };
globalThis.x86emuLog = () => {};

const mod = await createX86Emu();

// A guest that already exists on disk (generated by gen_elf_tests). Put it into
// MEMFS the way the page will put python313.dll etc.
const guestPath = path.join(root, 'tests/bin/hello_elf64');
if (!fs.existsSync(guestPath)) {
  console.error(`missing ${guestPath} - run: ./gen_elf_tests tests/bin`);
  process.exit(2);
}
mod.FS.mkdir('/work');
mod.FS.writeFile('/work/hello_elf64', new Uint8Array(fs.readFileSync(guestPath)));

// argv as a NUL-separated blob, argv[0] included.
const argv = ['hello_elf64', 'alpha', 'beta gamma'];
const enc = new TextEncoder().encode(argv.join('\0') + '\0');
const ap = mod._malloc(enc.length);
mod.HEAPU8.set(enc, ap);

out = '';
const code = mod.ccall('emu_run_path', 'number',
                       ['string', 'number', 'number', 'number', 'number'],
                       ['/work/hello_elf64', ap, enc.length, 0, 200000000]);
mod._free(ap);

const text = out.replace(/\r/g, '');
console.log('--- guest output ---');
process.stdout.write(text);
console.log('--- exit', code, '---');

const ok = code === 7 && text.includes('hello from the ELF guest!');
console.log(ok ? 'emu_run_path OK (loaded from MEMFS, ran with argv)'
               : 'FAIL: ' + (code < 0 ? mod.ccall('emu_error', 'string', [], []) : 'unexpected output/exit'));
process.exit(ok ? 0 : 1);
